#!/bin/bash
#SBATCH --job-name="dgemm_serial_sweep_runner"
#SBATCH --output="dgemm_serial_sweep_runner.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=32G
#SBATCH --account=ccu106
#SBATCH --export=ALL
#SBATCH -t 02:30:00

module purge
module load cpu
module load slurm
module load gcc
module load g++
module load openmpi


#Run the job
./matrix_multiplication_serial_blocked_runner